import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarDays, CalendarPlus, Clock3, BriefcaseBusiness, Settings2, LayoutDashboard, Store, ArrowLeft, Plus, Pencil, Trash2, X, Check, MessageCircle, Menu, ChevronRight, Users, Phone, Tag, CircleCheck, ExternalLink, Search, Filter, CalendarCheck2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AdminAccess } from "@/components/admin-access";

type Service = { id: string; name: string; category: string; description: string; duration: number; price: number; active: boolean };
type Day = { name: string; open: boolean; start: string; end: string };
type Appointment = { id: string; serviceId: string; serviceName: string; name: string; phone: string; date: string; time: string; status: "Confirmada" | "Cancelada" };
type Config = { name: string; logo: string; businessWhatsApp: string; supportWhatsApp: string };
type Data = { services: Service[]; days: Day[]; appointments: Appointment[]; config: Config };
type View = "inicio" | "catalogo" | "reservar" | "agenda" | "clientes" | "servicios" | "horarios" | "configuracion";

const initial: Data = {
  services: [
    { id: "1", name: "Limpieza dental", category: "Odontología", description: "Una limpieza profunda para cuidar tu sonrisa y mantener tu salud bucal.", duration: 45, price: 35, active: true },
    { id: "2", name: "Consulta general", category: "Odontología", description: "Evaluación completa y orientación personalizada para tu tratamiento.", duration: 30, price: 25, active: true },
    { id: "3", name: "Blanqueamiento dental", category: "Estética dental", description: "Tratamiento estético para una sonrisa más luminosa y natural.", duration: 60, price: 80, active: true },
    { id: "4", name: "Ortodoncia", category: "Especialidades", description: "Valoración inicial para alinear tu sonrisa con un plan a tu medida.", duration: 45, price: 50, active: true },
  ],
  days: [
    { name: "Lunes", open: true, start: "09:00", end: "18:00" }, { name: "Martes", open: true, start: "09:00", end: "18:00" },
    { name: "Miércoles", open: true, start: "09:00", end: "18:00" }, { name: "Jueves", open: true, start: "09:00", end: "18:00" },
    { name: "Viernes", open: true, start: "09:00", end: "18:00" }, { name: "Sábado", open: true, start: "09:00", end: "13:00" },
    { name: "Domingo", open: false, start: "09:00", end: "13:00" },
  ],
  appointments: [],
  config: { name: "Soluciones Digitales Caimán", logo: "", businessWhatsApp: "+5351234567", supportWhatsApp: "+5357654321" },
};
const dayIndex = (date: string) => { const d = new Date(`${date}T12:00:00`); return (d.getDay() + 6) % 7; };
const dateLabel = (date: string) => new Date(`${date}T12:00:00`).toLocaleDateString("es-ES", { day: "numeric", month: "long", year: "numeric" });
const whatsapp = (phone: string, text: string) => `https://wa.me/${phone.replace(/\D/g, "")}?text=${encodeURIComponent(text)}`;
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; };
const emptyService = (): Service => ({ id: "", name: "", category: "", description: "", duration: 30, price: 0, active: true });

export function TurnosApp({ isAdmin = false, onLogout }: { isAdmin?: boolean; onLogout?: () => void }) {
  const [data, setData] = useState<Data>(initial);
  const [loaded, setLoaded] = useState(false);
  const admin = isAdmin;
  const [view, setView] = useState<View>("inicio");
  const [menuOpen, setMenuOpen] = useState(false);
  const [booking, setBooking] = useState<Service | null>(null);
  const [date, setDate] = useState("");
  const [time, setTime] = useState("");
  const [clientName, setClientName] = useState("");
  const [clientPhone, setClientPhone] = useState("");
  const [success, setSuccess] = useState<Appointment | null>(null);
  const [editing, setEditing] = useState<Service | null>(null);
  const [category, setCategory] = useState("Todos");
  const [agendaFilter, setAgendaFilter] = useState("Todas");
  const [query, setQuery] = useState("");
  const [settings, setSettings] = useState<Config>(initial.config);
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    try { const stored = window.localStorage.getItem("caiman-turnos-v1"); if (stored) { const parsed = JSON.parse(stored) as Data; if (Array.isArray(parsed.services) && Array.isArray(parsed.days) && Array.isArray(parsed.appointments) && parsed.config) { setData(parsed); setSettings(parsed.config); } } } catch { /* retain defaults */ }
    setLoaded(true);
  }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem("caiman-turnos-v1", JSON.stringify(data)); }, [data, loaded]);

  const active = data.services.filter(s => s.active);
  const categories = ["Todos", ...new Set(active.map(s => s.category).filter(Boolean))];
  const filteredServices = active.filter(s => category === "Todos" || s.category === category);
  const upcoming = data.appointments.filter(a => a.status === "Confirmada" && `${a.date}T${a.time}` >= new Date().toISOString().slice(0,16)).sort((a,b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const selectedDay = date ? data.days[dayIndex(date)] : null;
  const slots = useMemo(() => {
    if (!date || !booking || !selectedDay?.open) return [];
    const start = Number(selectedDay.start.split(":")[0]) * 60 + Number(selectedDay.start.split(":")[1]);
    const end = Number(selectedDay.end.split(":")[0]) * 60 + Number(selectedDay.end.split(":")[1]);
    const result: string[] = [];
    for (let minute = start; minute + booking.duration <= end; minute += 30) {
      const slot = `${String(Math.floor(minute/60)).padStart(2,"0")}:${String(minute%60).padStart(2,"0")}`;
      const busy = data.appointments.some(a => a.date === date && a.status === "Confirmada" && minute < Number(a.time.slice(0,2))*60 + Number(a.time.slice(3))*1 + (data.services.find(s => s.id === a.serviceId)?.duration ?? 30) && minute + booking.duration > Number(a.time.slice(0,2))*60 + Number(a.time.slice(3)));
      if (!busy && new Date(`${date}T${slot}:00`) > new Date()) result.push(slot);
    }
    return result;
  }, [date, booking, selectedDay, data.appointments, data.services]);

  const openBooking = (service: Service) => { setBooking(service); setDate(""); setTime(""); setClientName(""); setClientPhone(""); setSuccess(null); };
  const submitBooking = (event: FormEvent) => {
    event.preventDefault();
    if (!booking || !date || !slots.includes(time) || !clientName.trim() || !clientPhone.trim()) return;
    const appointment: Appointment = { id: crypto.randomUUID(), serviceId: booking.id, serviceName: booking.name, name: clientName.trim(), phone: clientPhone.trim(), date, time, status: "Confirmada" };
    setData(previous => ({ ...previous, appointments: [...previous.appointments, appointment] }));
    setBooking(null); setSuccess(appointment);
  };
  const saveService = (event: FormEvent) => {
    event.preventDefault(); if (!editing || !editing.name.trim() || !editing.category.trim() || editing.duration < 1 || editing.price < 0) return;
    const service = { ...editing, name: editing.name.trim(), category: editing.category.trim(), id: editing.id || crypto.randomUUID() };
    setData(previous => ({ ...previous, services: editing.id ? previous.services.map(s => s.id === editing.id ? service : s) : [...previous.services, service] })); setEditing(null);
  };
  const updateDay = (i: number, changes: Partial<Day>) => setData(previous => ({ ...previous, days: previous.days.map((d, j) => i === j ? { ...d, ...changes } : d) }));
  const nav = (next: View) => { setView(next); setMenuOpen(false); };
  const businessMessage = (a: Appointment) => `Hola, quiero confirmar mi reserva.\nCliente: ${a.name}\nTeléfono: ${a.phone}\nServicio: ${a.serviceName}\nFecha: ${dateLabel(a.date)}\nHora: ${a.time}`;
  const clients = useMemo(() => {
    const map = new Map<string, { name: string; phone: string; visits: number; last: string }>();
    for (const a of data.appointments) {
      const key = a.phone || a.name;
      const prev = map.get(key);
      map.set(key, { name: a.name, phone: a.phone, visits: (prev?.visits ?? 0) + 1, last: prev && prev.last > `${a.date}T${a.time}` ? prev.last : `${a.date}T${a.time}` });
    }
    return [...map.values()].filter(c => !query.trim() || c.name.toLowerCase().includes(query.toLowerCase()) || c.phone.includes(query.trim())).sort((a, b) => b.last.localeCompare(a.last));
  }, [data.appointments, query]);
  const menuItems: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
    { id: "inicio", label: "Inicio", icon: LayoutDashboard }, { id: "catalogo", label: "Catálogo de servicios", icon: Store },
    { id: "reservar", label: "Reservar turno", icon: CalendarPlus }, { id: "agenda", label: "Agenda", icon: CalendarDays },
    { id: "clientes", label: "Clientes", icon: Users }, { id: "servicios", label: "Servicios", icon: BriefcaseBusiness },
    { id: "horarios", label: "Horarios", icon: Clock3 }, { id: "configuracion", label: "Configuración", icon: Settings2 },
  ];

  return <div className="min-h-screen bg-background font-sans">
    {admin ? <div className="min-h-screen lg:grid lg:grid-cols-[272px_minmax(0,1fr)]">
      {menuOpen && <div className="fixed inset-0 z-30 bg-foreground/40 lg:hidden" onClick={() => setMenuOpen(false)} />}
      <aside className={`fixed inset-y-0 left-0 z-40 flex w-[272px] flex-col bg-sidebar text-sidebar-foreground transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 ${menuOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="flex items-start justify-between px-5 pt-7 pb-6"><div className="min-w-0"><div className="mb-4 flex size-11 items-center justify-center rounded-lg bg-primary text-primary-foreground"><CalendarCheck2 size={23} /></div><h2 className="break-words text-lg font-bold leading-tight text-primary-foreground">{data.config.name}</h2><p className="mt-1 text-xs text-sidebar-foreground/75">Gestión simple de turnos</p></div><Button variant="ghost" size="icon" className="lg:hidden text-sidebar-foreground" onClick={() => setMenuOpen(false)} aria-label="Cerrar menú"><X /></Button></div>
        <div className="mx-5 border-t border-sidebar-foreground/20" />
        <nav className="flex-1 space-y-1 px-4 py-5" aria-label="Menú de administración">{menuItems.map(item => <Button key={item.id} variant="ghost" onClick={() => nav(item.id)} className={`h-11 w-full justify-start gap-3 px-4 text-[15px] font-medium text-sidebar-foreground hover:bg-sidebar-active hover:text-primary-foreground ${view === item.id ? "bg-sidebar-active text-primary-foreground" : ""}`}><item.icon size={19} />{item.label}</Button>)}</nav>
        <div className="mx-5 border-t border-sidebar-foreground/20 py-5"><p className="text-xs leading-relaxed text-sidebar-foreground/80">Desarrollado por Soluciones Digitales Caimán</p>{data.config.supportWhatsApp ? <a className="mt-1 inline-block text-sm font-bold underline underline-offset-2" target="_blank" rel="noreferrer" href={whatsapp(data.config.supportWhatsApp,"Hola, necesito soporte con el sistema de turnos.")}>Contactar Soporte</a> : <span className="mt-1 inline-block text-sm font-bold">Contactar Soporte</span>}<Button variant="outline" className="mt-6 w-full justify-start gap-2 border-sidebar-foreground/20 bg-sidebar-active text-sidebar-foreground hover:bg-sidebar-active hover:text-primary-foreground" onClick={() => { setMenuOpen(false); onLogout?.(); }}><ArrowLeft size={16} /> Cerrar sesión</Button></div>
      </aside>
      <main className="min-w-0 px-4 pb-16 pt-5 sm:px-8 lg:px-10 lg:pt-9 xl:px-12">
        <div className="mx-auto max-w-[1320px]">
          <header className="mb-8 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3"><div className="flex min-w-0 items-center gap-3"><Button variant="outline" size="icon" className="shrink-0 lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Abrir menú"><Menu /></Button><div className="min-w-0"><p className="mb-1 text-sm capitalize text-muted-foreground">{new Date().toLocaleDateString("es-ES", { weekday: "long", day: "numeric", month: "long" })}</p><h1 className="truncate text-2xl font-bold sm:text-3xl">{view === "inicio" ? "Hola, Administrador" : menuItems.find(i => i.id === view)?.label}</h1></div></div><div className="hidden items-center gap-2 rounded-full border bg-card px-3 py-2 text-xs font-medium shadow-sm sm:flex"><span className="size-2 rounded-full bg-success" /> Negocio disponible</div></header>
          {view === "inicio" && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Citas de hoy" value={data.appointments.filter(a => a.date === today() && a.status === "Confirmada").length} /><Stat label="Próximas citas" value={upcoming.length} /><Stat label="Servicios activos" value={active.length} /><Stat label="Estado de agenda" value={data.days[dayIndex(today())]?.open ? "Abierta" : "Cerrada"} highlight /></div><div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_0.95fr]"><section className="min-h-64 rounded-lg border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-bold">Próximos turnos</h2><Button variant="link" className="px-0" onClick={() => nav("agenda")}>Ver agenda <ChevronRight size={15} /></Button></div>{upcoming.length ? <div className="mt-5 divide-y">{upcoming.slice(0,4).map(a => <div key={a.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><p className="font-semibold">{a.name}</p><p className="text-sm text-muted-foreground">{a.serviceName}</p></div><p className="text-sm font-medium">{dateLabel(a.date)} · {a.time}</p></div>)}</div> : <p className="mt-10 text-muted-foreground">Aún no hay próximos turnos.</p>}</section><section className="rounded-lg border bg-card p-5 shadow-sm sm:p-6"><h2 className="mb-5 text-lg font-bold">Accesos rápidos</h2><div className="space-y-3"><Button className="h-11 w-full justify-start" onClick={() => nav("catalogo")}><Store /> Ver catálogo de servicios</Button><Button className="h-11 w-full justify-start bg-secondary text-secondary-foreground hover:bg-secondary/80" onClick={() => nav("reservar")}><Plus /> Reservar nuevo turno</Button><Button variant="outline" className="h-11 w-full justify-start" onClick={() => nav("servicios")}><BriefcaseBusiness /> Gestionar servicios</Button></div></section></div></>}
          {view === "catalogo" && <section><p className="mb-5 text-sm text-muted-foreground">Así ven tus clientes el catálogo público.</p>{categories.length > 2 && <div className="mb-6 flex flex-wrap gap-2" aria-label="Categorías">{categories.map(c => <Button key={c} size="sm" variant={category === c ? "default" : "outline"} onClick={() => setCategory(c)} className="rounded-full">{c}</Button>)}</div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredServices.map(s => <article key={s.id} className="flex min-h-56 flex-col rounded-lg border bg-card p-6 shadow-sm"><div className="mb-4 flex size-11 items-center justify-center rounded-md bg-tint text-primary"><BriefcaseBusiness size={22} /></div><p className="text-xs font-bold uppercase text-primary">{s.category}</p><h3 className="mt-2 text-xl font-bold">{s.name}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{s.description}</p><div className="mt-5 flex items-center gap-5 border-t pt-4 text-sm"><span className="flex items-center gap-1.5 text-muted-foreground"><Clock3 size={16} /> {s.duration} min</span><span className="ml-auto text-lg font-bold">${s.price}</span></div><Button className="mt-4 h-11 w-full" onClick={() => openBooking(s)}>Reservar turno <ChevronRight size={17} /></Button></article>)}</div>{!filteredServices.length && <div className="rounded-lg border bg-card px-5 py-16 text-center text-muted-foreground">No hay servicios disponibles.</div>}</section>}
          {view === "reservar" && <section><p className="mb-5 text-sm text-muted-foreground">Elige un servicio para registrar una cita en nombre de un cliente.</p><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{active.map(s => <button key={s.id} onClick={() => openBooking(s)} className="flex items-center gap-4 rounded-lg border bg-card p-5 text-left shadow-sm transition-shadow hover:shadow-md"><span className="flex size-11 shrink-0 items-center justify-center rounded-md bg-tint text-primary"><CalendarPlus size={20} /></span><span className="min-w-0"><span className="block truncate font-bold">{s.name}</span><span className="block text-sm text-muted-foreground">{s.duration} min · ${s.price}</span></span><ChevronRight size={18} className="ml-auto shrink-0 text-muted-foreground" /></button>)}</div>{!active.length && <div className="rounded-lg border bg-card px-5 py-16 text-center text-muted-foreground">No hay servicios activos. Activa uno en Servicios.</div>}</section>}
          {view === "clientes" && <section><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">Personas que han reservado turnos en tu negocio.</p><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input aria-label="Buscar cliente" placeholder="Buscar por nombre o teléfono" value={query} onChange={e => setQuery(e.target.value)} className="w-full pl-9 sm:w-72" /></div></div><div className="overflow-hidden rounded-lg border bg-card shadow-sm"><div className="divide-y">{clients.map(c => <div key={c.phone || c.name} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="min-w-0"><p className="font-semibold">{c.name}</p><p className="mt-0.5 flex items-center gap-1.5 text-sm text-muted-foreground"><Phone size={14} /> {c.phone || "Sin teléfono"}</p></div><div className="flex items-center gap-4 text-sm"><span className="rounded-full bg-tint px-2.5 py-1 text-xs font-semibold text-primary">{c.visits} {c.visits === 1 ? "cita" : "citas"}</span><span className="text-muted-foreground">Última: {dateLabel(c.last.slice(0,10))}</span>{c.phone && <Button asChild variant="outline" size="sm"><a target="_blank" rel="noreferrer" href={whatsapp(c.phone, `Hola ${c.name}, te contactamos de ${data.config.name}.`)}><MessageCircle /> WhatsApp</a></Button>}</div></div>)}{!clients.length && <div className="px-5 py-16 text-center"><Users className="mx-auto mb-3 text-muted-foreground" size={30} /><p className="text-muted-foreground">{query ? "Sin resultados para tu búsqueda." : "Aún no hay clientes registrados."}</p></div>}</div></div></section>}
          {view === "agenda" && <section><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">Controla todas las reservas de tu negocio.</p><div className="flex items-center gap-2"><Filter size={16} className="text-muted-foreground" /><select aria-label="Filtrar citas" value={agendaFilter} onChange={e => setAgendaFilter(e.target.value)} className="h-10 rounded-md border bg-card px-3 text-sm"><option>Todas</option><option>Confirmadas</option><option>Canceladas</option></select></div></div><div className="overflow-hidden rounded-lg border bg-card shadow-sm"><div className="divide-y">{data.appointments.filter(a => agendaFilter === "Todas" || (agendaFilter === "Confirmadas" ? a.status === "Confirmada" : a.status === "Cancelada")).sort((a,b) => `${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`)).map(a => <div key={a.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>{a.name}</strong><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${a.status === "Confirmada" ? "bg-tint text-primary" : "bg-muted text-muted-foreground"}`}>{a.status}</span></div><p className="mt-1 text-sm text-muted-foreground">{a.serviceName} · {a.phone}</p><p className="mt-1 text-sm font-medium">{dateLabel(a.date)} · {a.time}</p></div>{a.status === "Confirmada" && <Button variant="outline" size="sm" onClick={() => setData(p => ({ ...p, appointments: p.appointments.map(item => item.id === a.id ? { ...item, status: "Cancelada" } : item) }))}>Cancelar cita</Button>}</div>)}{!data.appointments.filter(a => agendaFilter === "Todas" || (agendaFilter === "Confirmadas" ? a.status === "Confirmada" : a.status === "Cancelada")).length && <div className="px-5 py-16 text-center"><CalendarDays className="mx-auto mb-3 text-muted-foreground" size={30} /><p className="text-muted-foreground">No hay turnos para mostrar.</p></div>}</div></div></section>}
          {view === "servicios" && <section><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm text-muted-foreground">Crea y administra los servicios que ven tus clientes.</p><Button onClick={() => setEditing(emptyService())}><Plus /> Añadir nuevo servicio</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.services.map(s => <article key={s.id} className="flex flex-col rounded-lg border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-2"><span className="rounded bg-tint px-2 py-1 text-xs font-semibold text-primary">{s.category}</span><span className={`rounded-full px-2 py-1 text-xs font-semibold ${s.active ? "bg-tint text-primary" : "bg-muted text-muted-foreground"}`}>{s.active ? "Activo" : "Inactivo"}</span></div><h3 className="mt-4 text-lg font-bold">{s.name}</h3><p className="mt-2 min-h-12 flex-1 text-sm text-muted-foreground">{s.description}</p><p className="mt-4 text-sm font-semibold">{s.duration} min <span className="mx-2 text-muted-foreground">·</span> ${s.price}</p><div className="mt-5 flex gap-2 border-t pt-4"><Button variant="outline" size="sm" onClick={() => setEditing({ ...s })}><Pencil /> Editar</Button><Button variant="ghost" size="sm" className="text-destructive hover:text-destructive" onClick={() => { if (window.confirm(`¿Eliminar ${s.name}?`)) setData(p => ({ ...p, services: p.services.filter(item => item.id !== s.id) })); }}><Trash2 /> Eliminar</Button></div></article>)}</div></section>}
          {view === "horarios" && <section><p className="mb-5 text-sm text-muted-foreground">Define los días y horas disponibles para las reservas.</p><div className="overflow-hidden rounded-lg border bg-card shadow-sm">{data.days.map((d,i) => <div key={d.name} className="grid gap-3 border-b p-4 last:border-b-0 sm:grid-cols-[160px_1fr_auto] sm:items-center sm:gap-5 sm:px-6"><div className="flex items-center justify-between gap-3"><strong>{d.name}</strong><span className={`text-xs font-medium sm:hidden ${d.open ? "text-primary" : "text-muted-foreground"}`}>{d.open ? "Abierto" : "Cerrado"}</span></div><div className="flex items-center gap-2"><Input aria-label={`Inicio ${d.name}`} type="time" value={d.start} disabled={!d.open} onChange={e => updateDay(i,{start:e.target.value})} className="max-w-32" /><span className="text-muted-foreground">a</span><Input aria-label={`Fin ${d.name}`} type="time" value={d.end} disabled={!d.open} onChange={e => updateDay(i,{end:e.target.value})} className="max-w-32" /></div><div className="flex items-center justify-between gap-3 sm:justify-end"><span className="text-xs text-muted-foreground">{d.open ? "Abierto" : "Cerrado"}</span><Switch aria-label={`${d.name} abierto`} checked={d.open} onCheckedChange={checked => updateDay(i,{open:checked})} /></div></div>)}</div></section>}
          {view === "configuracion" && <section className="max-w-2xl"><p className="mb-5 text-sm text-muted-foreground">Personaliza la identidad y los datos de contacto del negocio.</p><form onSubmit={e => { e.preventDefault(); setData(p => ({ ...p, config: settings })); setSaved(true); window.setTimeout(() => setSaved(false), 3000); }} className="space-y-6 rounded-lg border bg-card p-5 shadow-sm sm:p-7"><Field label="Nombre del negocio"><Input required value={settings.name} onChange={e => setSettings({ ...settings, name: e.target.value })} /></Field><Field label="Logo del negocio"><div className="flex items-center gap-4">{settings.logo ? <img src={settings.logo} alt="Logo del negocio" className="size-16 rounded-md border object-cover" /> : <div className="flex size-16 items-center justify-center rounded-md border bg-muted text-muted-foreground"><Store /></div>}<Input aria-label="Subir logo" type="file" accept="image/*" onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1500000) { window.alert("El logo debe pesar menos de 1.5 MB."); return; } const reader = new FileReader(); reader.onload = () => setSettings(p => ({ ...p, logo: String(reader.result ?? "") })); reader.readAsDataURL(file); }} className="h-auto max-w-sm py-2" /></div></Field><div className="border-t pt-5"><Field label="WhatsApp del negocio" hint="Recibe los detalles de las reservas y los mensajes de tus clientes."><Input type="tel" placeholder="Ej. +53 5 123 4567" value={settings.businessWhatsApp} onChange={e => setSettings({ ...settings, businessWhatsApp: e.target.value })} /></Field></div><Field label="Soporte técnico del sistema" hint="Número independiente para el enlace de soporte."><Input type="tel" placeholder="Ej. +53 5 765 4321" value={settings.supportWhatsApp} onChange={e => setSettings({ ...settings, supportWhatsApp: e.target.value })} /></Field><div className="flex items-center gap-3 border-t pt-5"><Button type="submit"><Check /> Guardar cambios</Button>{saved && <span className="text-sm font-medium text-primary">Cambios guardados</span>}</div></form>{admin && <AdminAccess />}</section>}
        </div>
      </main>
    </div> : <div className="min-h-screen"><header className="border-b bg-card"><div className="mx-auto flex max-w-[1320px] items-center justify-between gap-4 px-5 py-4 sm:px-8 lg:px-12"><div className="flex min-w-0 items-center gap-3">{data.config.logo ? <img src={data.config.logo} alt="Logo" className="size-11 shrink-0 rounded-md object-cover" /> : <div className="flex size-11 shrink-0 items-center justify-center rounded-lg bg-primary text-primary-foreground"><CalendarCheck2 size={23} /></div>}<div className="min-w-0"><p className="truncate text-base font-bold leading-tight sm:text-lg">{data.config.name}</p><p className="text-xs text-muted-foreground">Reserva tu próximo turno</p></div></div></div></header><main className="mx-auto max-w-[1320px] px-5 pb-28 pt-10 sm:px-8 sm:pt-14 lg:px-12"><div className="mb-8"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-primary"><span className="size-2 rounded-full bg-success" /> Agenda abierta para reservas</div><h1 className="text-3xl font-bold sm:text-4xl">Nuestros servicios</h1><p className="mt-3 max-w-xl text-base text-muted-foreground">Elige el servicio que necesitas y encuentra un horario disponible para ti.</p></div>{categories.length > 2 && <div className="mb-7 flex flex-wrap gap-2" aria-label="Categorías">{categories.map(c => <Button key={c} size="sm" variant={category === c ? "default" : "outline"} onClick={() => setCategory(c)} className="rounded-full">{c}</Button>)}</div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filteredServices.map(s => <article key={s.id} className="flex min-h-64 flex-col rounded-lg border bg-card p-6 shadow-sm transition-shadow hover:shadow-md"><div className="mb-5 flex size-11 items-center justify-center rounded-md bg-tint text-primary"><BriefcaseBusiness size={22} /></div><p className="text-xs font-bold uppercase text-primary">{s.category}</p><h2 className="mt-2 text-xl font-bold">{s.name}</h2><p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">{s.description}</p><div className="mt-6 flex items-center gap-5 border-t pt-5 text-sm"><span className="flex items-center gap-1.5 text-muted-foreground"><Clock3 size={16} /> {s.duration} min</span><span className="ml-auto text-lg font-bold">${s.price}</span></div><Button className="mt-5 h-11 w-full" onClick={() => openBooking(s)}>Reservar turno <ChevronRight size={17} /></Button></article>)}</div>{!filteredServices.length && <div className="rounded-lg border bg-card px-5 py-16 text-center text-muted-foreground">No hay servicios disponibles en este momento.</div>}</main><footer className="border-t bg-card px-5 py-6 text-center text-xs text-muted-foreground">Desarrollado por Soluciones Digitales Caimán {data.config.supportWhatsApp && <>· <a className="font-semibold text-primary underline" target="_blank" rel="noreferrer" href={whatsapp(data.config.supportWhatsApp,"Hola, necesito soporte con el sistema de turnos.")}>Contactar Soporte</a></>}</footer></div>}
    {data.config.businessWhatsApp && <a href={whatsapp(data.config.businessWhatsApp,"Hola, quisiera consultar sobre los turnos disponibles.")} target="_blank" rel="noreferrer" aria-label="Contactar al negocio por WhatsApp" title="Contactar por WhatsApp" className="fixed bottom-5 right-5 z-20 flex size-14 items-center justify-center rounded-full bg-success text-success-foreground shadow-lg transition-transform hover:scale-105"><MessageCircle size={26} /></a>}
    <Dialog open={!!booking} onOpenChange={open => { if (!open) setBooking(null); }}><DialogContent className="max-h-[90vh] w-[calc(100%-2rem)] max-w-lg overflow-y-auto rounded-lg"><DialogHeader><DialogTitle>Reservar turno</DialogTitle><DialogDescription>{booking?.name} · {booking?.duration} min · ${booking?.price}</DialogDescription></DialogHeader><form onSubmit={submitBooking} className="space-y-5 pt-2"><Field label="Fecha"><Input type="date" required min={today()} value={date} onChange={e => { setDate(e.target.value); setTime(""); }} /></Field>{date && !selectedDay?.open && <p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">El negocio está cerrado este día. Elige otra fecha.</p>}{date && selectedDay?.open && <div><p className="mb-2 text-sm font-medium">Hora disponible</p>{slots.length ? <div className="grid grid-cols-3 gap-2 sm:grid-cols-4">{slots.map(slot => <Button key={slot} type="button" variant={time === slot ? "default" : "outline"} size="sm" onClick={() => setTime(slot)}>{slot}</Button>)}</div> : <p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">No hay horarios disponibles para esta fecha.</p>}</div>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Tu nombre"><Input required value={clientName} onChange={e => setClientName(e.target.value)} placeholder="Nombre completo" /></Field><Field label="Tu teléfono"><Input required type="tel" value={clientPhone} onChange={e => setClientPhone(e.target.value)} placeholder="Número de contacto" /></Field></div><Button type="submit" className="h-11 w-full" disabled={!time || !slots.includes(time)}>Confirmar cita</Button></form></DialogContent></Dialog>
    <Dialog open={!!success} onOpenChange={open => { if (!open) setSuccess(null); }}><DialogContent className="w-[calc(100%-2rem)] max-w-md rounded-lg"><DialogHeader><div className="mb-2 flex size-12 items-center justify-center rounded-full bg-tint text-primary"><CircleCheck /></div><DialogTitle>¡Tu cita está reservada!</DialogTitle><DialogDescription>{success?.serviceName} · {success ? dateLabel(success.date) : ""} a las {success?.time}</DialogDescription></DialogHeader><p className="text-sm text-muted-foreground">Tu turno quedó registrado. Comparte los detalles con el negocio por WhatsApp para avisarle.</p>{data.config.businessWhatsApp ? <Button asChild className="h-11 w-full"><a target="_blank" rel="noreferrer" href={success ? whatsapp(data.config.businessWhatsApp,businessMessage(success)) : "#"}><MessageCircle /> Enviar por WhatsApp <ExternalLink size={15} /></a></Button> : <p className="rounded-md bg-muted p-3 text-sm text-muted-foreground">El WhatsApp del negocio aún no está configurado.</p>}</DialogContent></Dialog>
    <Dialog open={!!editing} onOpenChange={open => { if (!open) setEditing(null); }}><DialogContent className="max-h-[90vh] w-[calc(100%-2rem)] max-w-lg overflow-y-auto rounded-lg"><DialogHeader><DialogTitle>{editing?.id ? "Editar servicio" : "Añadir nuevo servicio"}</DialogTitle><DialogDescription>Completa los datos del servicio.</DialogDescription></DialogHeader>{editing && <form onSubmit={saveService} className="space-y-4 pt-2"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><Input required value={editing.name} onChange={e => setEditing({...editing,name:e.target.value})} /></Field><Field label="Categoría"><Input required value={editing.category} onChange={e => setEditing({...editing,category:e.target.value})} /></Field></div><Field label="Descripción"><textarea className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-ring" value={editing.description} onChange={e => setEditing({...editing,description:e.target.value})} /></Field><div className="grid grid-cols-2 gap-4"><Field label="Duración (min)"><Input required min="1" type="number" value={editing.duration} onChange={e => setEditing({...editing,duration:Number(e.target.value)})} /></Field><Field label="Precio ($)"><Input required min="0" step="0.01" type="number" value={editing.price} onChange={e => setEditing({...editing,price:Number(e.target.value)})} /></Field></div><div className="flex items-center justify-between rounded-md border p-3"><div><p className="text-sm font-semibold">Servicio activo</p><p className="text-xs text-muted-foreground">Visible para los clientes</p></div><Switch aria-label="Servicio activo" checked={editing.active} onCheckedChange={checked => setEditing({...editing,active:checked})} /></div><Button type="submit" className="h-11 w-full">Guardar servicio</Button></form>}</DialogContent></Dialog>
  </div>;
}
function Stat({label,value,highlight=false}:{label:string;value:string|number;highlight?:boolean}) { return <div className="min-h-28 rounded-lg border bg-card p-5 shadow-sm"><p className="text-sm text-muted-foreground">{label}</p><p className={`mt-3 text-2xl font-bold ${highlight ? "text-primary" : ""}`}>{value}</p></div>; }
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}) { return <label className="block space-y-2"><span className="block text-sm font-semibold">{label}</span>{hint && <span className="block text-xs text-muted-foreground">{hint}</span>}{children}</label>; }
